services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
      target: dev # Usa la fase di sviluppo del Dockerfile
    volumes:
      - ./backend:/app:delegated # Monta il codice sorgente per hot reload
      - ./backend/bin:/app/bin
    working_dir: /app
    command: air -c .air.toml
    ports:
      - "8181:8181"
    environment:
      - ENV=development

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
      target: development # Usa la fase di sviluppo del Dockerfile
    volumes:
      - ./frontend:/app # Monta il codice sorgente per hot reload
      - /app/node_modules
    command: npm run dev -- --host
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
