services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
      target: production
    ports:
      - "8181:8181"
    environment:
      - ENV=production

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
      target: production
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
