# Imposta la directory principale
root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o /app/bin/estimator ./cmd/app/main.go"
  bin = "/app/bin/estimator"
  kill = true
  include_dir = ["."]
  exclude_dir = ["tmp", "vendor"]
[log]
  time = true
  color = true
[watcher]
  poll = true  # Forza il polling
  interval = 1000  # Imposta l'intervallo di polling (in millisecondi)